### ISSUE TITLE
not compatible with redmine 4

### ISSUE THREAD

**Issue by goutnet** [jmlagace/redmine_home_page_redirector#2]
Hi,
this plugin breaks on redmine 4:

```
rake aborted!
NoMethodError: undefined method `alias_method_chain' for WelcomeController:Class
Did you mean?  alias_method
plugins/redmine_home_page_redirector/lib/home_page_redirector.rb:13:in `block in included'
plugins/redmine_home_page_redirector/lib/home_page_redirector.rb:4:in `class_eval'
plugins/redmine_home_page_redirector/lib/home_page_redirector.rb:4:in `included'
plugins/redmine_home_page_redirector/init.rb:21:in `include'
plugins/redmine_home_page_redirector/init.rb:21:in `block (2 levels) in <top (required)>'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `instance_exec'
/srv/unfreeze/redmine/vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
vendor/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:89:in `prepare!'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
config/environment.rb:14:in `<top (required)>'
vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
vendor/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:337:in `require_environment!'
vendor/ruby/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
vendor/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
```

could you spare some time to fix it?

**Comment by jmlagace** [comment]
Hello Florian,

It won't be before the weekend but I can give it a try.

To recap you are using ruby 2.3 and Redmine 4?


--
Jean-Marc Lagacé
entrepreneur, propriétaire :: M2i3.com
about.me/jeanmarc.lagace <https://about.me/jeanmarc.lagace?promo=email_sig>
 :: jean-marc@m2i3.com :: http://m2i3.com :: +1.888.403.5998 x101
<+18884035998,,101>

**Comment by goutnet** [comment]
Redmine 4.0.1 and ruby 2.3.0 yes :)

**Comment by jmlagace** [comment]
@goutnet, just finishing  addressing the problem. In the end it was linked to the version of Ruby and not Redmine per say. I'm glad the plugin is helping out.
