### ISSUE TITLE
Plugin broken on Redmine v5

### ISSUE THREAD

**Issue by Coolfeather2** [jmlagace/redmine_home_page_redirector#4]
There doesn't seem to be a specific error message outlining the issue to diagnose this?
Let me know if I can provide any further information to assist with this

Output from `bundle exec rake redmine:plugins`:
```
rake aborted!
LoadError: cannot load such file -- home_page_redirector
C:/redmine-5.0.3/plugins/redmine_home_page_redirector/init.rb:9:in `block in <top (required)>'
C:/redmine-5.0.3/lib/redmine/plugin.rb:96:in `instance_eval'
C:/redmine-5.0.3/lib/redmine/plugin.rb:96:in `register'
C:/redmine-5.0.3/plugins/redmine_home_page_redirector/init.rb:1:in `<top (required)>'
C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `load'
C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `run_initializer'
C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `each'
C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `block in load'
C:/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
C:/redmine-5.0.3/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

Output from running webserver:
```
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require': cannot load such file -- home_page_redirector (LoadError)
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
	from C:/redmine-5.0.3/plugins/redmine_home_page_redirector/init.rb:9:in `block in <top (required)>'
	from C:/redmine-5.0.3/lib/redmine/plugin.rb:96:in `instance_eval'
	from C:/redmine-5.0.3/lib/redmine/plugin.rb:96:in `register'
	from C:/redmine-5.0.3/plugins/redmine_home_page_redirector/init.rb:1:in `<top (required)>'
	from C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `load'
	from C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:31:in `run_initializer'
	from C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `each'
	from C:/redmine-5.0.3/lib/redmine/plugin_loader.rb:108:in `block in load'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:347:in `each'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:347:in `call'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
	from C:/Ruby31-x64/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	from C:/redmine-5.0.3/config/environment.rb:16:in `<top (required)>'
	from <internal:C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:C:/Ruby31-x64/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from config.ru:3:in `block in <main>'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:364:in `load_rackup'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:286:in `app'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/runner.rb:158:in `load_and_bind'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/single.rb:44:in `run'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/launcher.rb:186:in `run'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/cli.rb:75:in `run'
	from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/puma-6.0.0/bin/puma:10:in `<top (required)>'
	from C:/Ruby31-x64/bin/puma:32:in `load'
	from C:/Ruby31-x64/bin/puma:32:in `<main>'
```

system information:
```
Environment:
  Redmine version                5.0.3.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x64-mingw-ucrt]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               SQLServer
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.6.4
```

**Comment by muradurm** [comment]
Edit file init.rb, replace string
_require_dependency 'home_page_redirector'_
to
`require_dependency File.dirname(__FILE__) + '/lib/' + 'home_page_redirector'`

**Comment by Coolfeather2** [comment]
I used #5  to resolve my issue
